/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Language: typeof import('./src/components/language/index.vue')['default']
    LoginRequired: typeof import('./src/components/authentication/login-required.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
  }
}

// For TSX support
declare global {
  const Language: (typeof import('./src/components/language/index.vue'))['default'];
  const LoginRequired: (typeof import('./src/components/authentication/login-required.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const VanActionSheet: (typeof import('vant/es'))['ActionSheet'];
  const VanButton: (typeof import('vant/es'))['Button'];
  const VanCell: (typeof import('vant/es'))['Cell'];
  const VanCellGroup: (typeof import('vant/es'))['CellGroup'];
  const VanConfigProvider: (typeof import('vant/es'))['ConfigProvider'];
  const VanEmpty: (typeof import('vant/es'))['Empty'];
  const VanField: (typeof import('vant/es'))['Field'];
  const VanForm: (typeof import('vant/es'))['Form'];
  const VanNavBar: (typeof import('vant/es'))['NavBar'];
  const VanRadio: (typeof import('vant/es'))['Radio'];
  const VanRadioGroup: (typeof import('vant/es'))['RadioGroup'];
  const VanSkeleton: (typeof import('vant/es'))['Skeleton'];
}
